// This file was autogenerated by /home/energy/Workspace/HitTheZombie/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/game.js', ['energy.zombie', 'energy.zombie.Game'], ['energy.zombie.Target', 'goog.Timer', 'goog.array', 'goog.dom', 'goog.dom.classes', 'goog.style', 'goog.ui.Slider']);
goog.addDependency('../../../../js/target.js', ['energy.zombie.Target'], ['goog.dom', 'goog.dom.classes', 'goog.events', 'goog.style']);
