// This file was autogenerated by C:\Program Files\Closure\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/deps.js', [], []);
goog.addDependency('../../../../js/useragent.js', ['energy.userAgent'], ['goog.userAgent']);
goog.addDependency('../../../../js/zombie/game.js', ['energy.zombie', 'energy.zombie.Game'], ['energy.zombie.Target', 'goog.Timer', 'goog.array', 'goog.dom', 'goog.dom.classes', 'goog.style', 'goog.userAgent.product']);
goog.addDependency('../../../../js/zombie/target.js', ['energy.zombie.Target'], ['goog.dom', 'goog.dom.classes', 'goog.events', 'goog.style', 'goog.userAgent', 'goog.userAgent.product']);
